export const GET_CURRENT_LOCATION_WEATHER_REQUEST = "@@REDUCER/GET_CURRENT_LOCATION_WEATHER_REQUEST"
export const GET_CURRENT_LOCATION_WEATHER_SUCCESS = "@@REDUCER/GET_CURRENT_LOCATION_WEATHER_SUCCESS"
export const GET_CURRENT_LOCATION_WEATHER_FAIL = "@@REDUCER/GET_CURRENT_LOCATION_WEATHER_FAIL"

export const GET_LOCATION_REQUEST = "@@REDUCER/GET_LOCATION_REQUEST"
export const GET_LOCATION_SUCCESS = "@@REDUCER/GET_LOCATION_SUCCESS"
export const GET_LOCATION_FAIL = "@@REDUCER/GET_LOCATION_FAIL"

export const GET_FORECAST_REQUEST = "@@REDUCER/GET_FORECAST_REQUEST"
export const GET_FORECAST_SUCCESS = "@@REDUCER/GET_FORECAST_SUCCESS"
export const GET_FORECAST_FAIL = "@@REDUCER/GET_FORECAST_FAIL"