export const GET_CURRENT_LOCATION_WEATHER_REQUEST = "@@REDUCER/GET_CURRENT_LOCATION_WEATHER_REQUEST"
export const GET_CURRENT_LOCATION_WEATHER_SUCCESS = "@@REDUCER/GET_CURRENT_LOCATION_WEATHER_SUCCESS"
export const GET_CURRENT_LOCATION_WEATHER_FAIL = "@@REDUCER/GET_CURRENT_LOCATION_WEATHER_FAIL"

export const GET_WEATHER_FORECAST_REQUEST = "@@REDUCER/GET_WEATHER_FORECAST_REQUEST"
export const GET_WEATHER_FORECAST_SUCCESS = "@@REDUCER/GET_WEATHER_FORECAST_SUCCESS"
export const GET_WEATHER_FORECAST_FAIL = "@@REDUCER/GET_WEATHER_FORECAST_FAIL"